[package]
name = "quelparti"
version = "0.0.1"
edition = "2018"

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.9"
actix-session = "0.5.0-beta.2"
actix-files = "0.6.0-beta.7"
awc = { version = "3.0.0-beta.8", features = ["rustls"] }
serde = "1.0"
serde_json = "1.0"
base64 = "0.13"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono", "network-address"] }
diesel_migrations = "1.4"
ipnetwork = "0.18"
csrf = "0.4"
once_cell = "1.8"
csv = "1.1"
toml = "0.5"
